### PR TITLE
feat: automate the build

### PR DESCRIPTION
**Pull request by gsdevme**
Hey @andrew-canaday 

In regard to https://github.com/NYTimes/libvmod-queryfilter/issues/2 

Ive create a travis file and using kitchen-ci set it to build the package on both CentOS & Debian... likely some more work but just thought Id push the changes to get some thoughts? 

I've ran both suites and screenshot the errors, Debian seems to get further than CentOS though but fails at the `make` point. 

CentOS 6.9
screen shot 2018-01-30 at 21 16 16

Debian 8
screen shot 2018-01-30 at 21 20 54

I also checked the folder you was speaking about.

```
root@674f4c3ba5ab:~# ls -l /usr/include/varnish/
total 140
drwxr-xr-x 2 root root  4096 Jan 30 21:20 cache
drwxr-xr-x 2 root root  4096 Jan 30 21:20 common
-rw-r--r-- 1 root root  1981 Nov 14 15:27 miniobj.h
drwxr-xr-x 2 root root  4096 Jan 30 21:20 tbl
drwxr-xr-x 2 root root  4096 Jan 30 21:20 vapi
-rw-r--r-- 1 root root  3128 Nov 14 15:27 vas.h
-rw-r--r-- 1 root root  1727 Nov 14 15:27 vav.h
-rw-r--r-- 1 root root  4339 Nov 14 15:27 vbm.h
-rw-r--r-- 1 root root  2194 Nov 14 15:27 vcl.h
-rw-r--r-- 1 root root  2572 Nov 14 15:27 vcli.h
-rw-r--r-- 1 root root  1553 Nov 14 15:27 vcs.h
-rw-r--r-- 1 root root  4534 Nov 14 15:27 vdef.h
-rw-r--r-- 1 root root   163 Nov 14 15:27 vmod_abi.h
-rw-r--r-- 1 root root 19914 Nov 14 15:27 vqueue.h
-rw-r--r-- 1 root root  2257 Nov 14 15:27 vre.h
-rw-r--r-- 1 root root  1637 Nov 14 15:27 vrnd.h
-rw-r--r-- 1 root root 10615 Nov 14 15:27 vrt.h
-rw-r--r-- 1 root root  4963 Nov 14 15:27 vrt_obj.h
-rw-r--r-- 1 root root  2235 Nov 14 15:27 vsa.h
-rw-r--r-- 1 root root  3389 Nov 14 15:27 vsb.h
-rw-r--r-- 1 root root  1828 Nov 14 15:27 vsha256.h
-rw-r--r-- 1 root root  2803 Nov 14 15:27 vtcp.h
-rw-r--r-- 1 root root  1740 Nov 14 15:27 vtim.h
-rw-r--r-- 1 root root  2659 Nov 14 15:27 vut.h
-rw-r--r-- 1 root root  3616 Nov 14 15:27 vut_options.h
drwxr-xr-x 2 root root  4096 Jan 30 21:20 waiter
```

### CODE REVIEW

**Comment by gsdevme** [comment]
So I've installed Varnish from the package, then downloaded the source files and done as suggested, however it still won't get past `./configure` :( for CentOS 6.9 @andrew-canaday 

```
       Package varnish-4.1.9-1.el6.x86_64 already installed and latest version
       Nothing to do
       --2018-02-01 23:37:13--  https://github.com/varnishcache/varnish-cache/archive/varnish-4.1.9.tar.gz
       Resolving github.com... 192.30.253.112, 192.30.253.113
       Connecting to github.com|192.30.253.112|:443... connected.
       HTTP request sent, awaiting response... 302 Found
       Location: https://codeload.github.com/varnishcache/varnish-cache/tar.gz/varnish-4.1.9 [following]
       --2018-02-01 23:37:14--  https://codeload.github.com/varnishcache/varnish-cache/tar.gz/varnish-4.1.9
       Resolving codeload.github.com... 192.30.253.120, 192.30.253.121
       Connecting to codeload.github.com|192.30.253.120|:443... connected.
       HTTP request sent, awaiting response... 200 OK
       Length: 949367 (927K) [application/x-gzip]
       Saving to: “varnish-4.1.9.tar.gz.1”

100%[======================================>] 949,367      734K/s   in 1.3s

       2018-02-01 23:37:16 (734 KB/s) - “varnish-4.1.9.tar.gz.1” saved [949367/949367]

       + libtoolize --copy --force
       libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
       libtoolize: copying file `build-aux/ltmain.sh'
       libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
       libtoolize: copying file `m4/libtool.m4'
       libtoolize: copying file `m4/ltoptions.m4'
       libtoolize: copying file `m4/ltsugar.m4'
       libtoolize: copying file `m4/ltversion.m4'
       libtoolize: copying file `m4/lt~obsolete.m4'
       + aclocal -I m4
       configure.ac:25: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       ../../lib/autoconf/specific.m4:386: AC_USE_SYSTEM_EXTENSIONS is expanded from...
       ../../lib/autoconf/specific.m4:332: AC_GNU_SOURCE is expanded from...
       configure.ac:25: the top level
       configure.ac:25: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       + autoheader
       configure.ac:25: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       ../../lib/autoconf/specific.m4:386: AC_USE_SYSTEM_EXTENSIONS is expanded from...
       ../../lib/autoconf/specific.m4:332: AC_GNU_SOURCE is expanded from...
       configure.ac:25: the top level
       configure.ac:25: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       + automake --add-missing --copy --foreign
       configure.ac:25: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       ../../lib/autoconf/specific.m4:386: AC_USE_SYSTEM_EXTENSIONS is expanded from...
       ../../lib/autoconf/specific.m4:332: AC_GNU_SOURCE is expanded from...
       configure.ac:25: the top level
       configure.ac:25: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       + autoconf
       configure.ac:25: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       ../../lib/autoconf/specific.m4:386: AC_USE_SYSTEM_EXTENSIONS is expanded from...
       ../../lib/autoconf/specific.m4:332: AC_GNU_SOURCE is expanded from...
       configure.ac:25: the top level
       configure.ac:25: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
       checking for gcc... gcc
       checking for C compiler default output file name... a.out
       checking whether the C compiler works... yes
       checking whether we are cross compiling... no
       checking for suffix of executables...
       checking for suffix of object files... o
       checking whether we are using the GNU C compiler... yes
       checking whether gcc accepts -g... yes
       checking for gcc option to accept ISO C89... none needed
       checking how to run the C preprocessor... gcc -E
       checking for grep that handles long lines and -e... /bin/grep
       checking for egrep... /bin/grep -E
       checking for ANSI C header files... yes
       checking for sys/types.h... yes
       checking for sys/stat.h... yes
       checking for stdlib.h... yes
       checking for string.h... yes
       checking for memory.h... yes
       checking for strings.h... yes
       checking for inttypes.h... yes
       checking for stdint.h... yes
       checking for unistd.h... yes
       checking minix/config.h usability... no
       checking minix/config.h presence... no
       checking for minix/config.h... no
       checking whether it is safe to define __EXTENSIONS__... yes
       checking build system type... x86_64-unknown-linux-gnu
       checking host system type... x86_64-unknown-linux-gnu
       checking target system type... x86_64-unknown-linux-gnu
       checking whether to enable maintainer-specific portions of Makefiles... no
       checking for a BSD-compatible install... /usr/bin/install -c
       checking whether build environment is sane... yes
       checking for a thread-safe mkdir -p... /bin/mkdir -p
       checking for gawk... gawk
       checking whether make sets $(MAKE)... yes
       checking for style of include used by make... GNU
       checking dependency style of gcc... gcc3
       checking for a sed that does not truncate output... /bin/sed
       checking for fgrep... /bin/grep -F
       checking for ld used by gcc... /usr/bin/ld
       checking if the linker (/usr/bin/ld) is GNU ld... yes
       checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
       checking the name lister (/usr/bin/nm -B) interface... BSD nm
       checking whether ln -s works... yes
       checking the maximum length of command line arguments... 1572864
       checking whether the shell understands some XSI constructs... yes
       checking whether the shell understands "+="... yes
       checking for /usr/bin/ld option to reload object files... -r
       checking for objdump... objdump
       checking how to recognize dependent libraries... pass_all
       checking for ar... ar
       checking for strip... strip
       checking for ranlib... ranlib
       checking command to parse /usr/bin/nm -B output from gcc object... ok
       checking for dlfcn.h... yes
       checking for objdir... .libs
       checking if gcc supports -fno-rtti -fno-exceptions... no
       checking for gcc option to produce PIC... -fPIC -DPIC
       checking if gcc PIC flag -fPIC -DPIC works... yes
       checking if gcc static flag -static works... no
       checking if gcc supports -c -o file.o... yes
       checking if gcc supports -c -o file.o... (cached) yes
       checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
       checking whether -lc should be explicitly linked in... no
       checking dynamic linker characteristics... GNU/Linux ld.so
       checking how to hardcode library paths into programs... immediate
       checking whether stripping libraries is possible... yes
       checking if libtool supports shared libraries... yes
       checking whether to build shared libraries... yes
       checking whether to build static libraries... no
       checking for minix/config.h... (cached) no
       checking whether it is safe to define __EXTENSIONS__... (cached) yes
       checking for gcc... (cached) gcc
       checking whether we are using the GNU C compiler... (cached) yes
       checking whether gcc accepts -g... (cached) yes
       checking for gcc option to accept ISO C89... (cached) none needed
       checking for gcc option to accept ISO C99... -std=gnu99
       checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
       checking how to run the C preprocessor... gcc -E
       checking for the pthreads library -lpthreads... no
       checking whether pthreads work without any flags... no
       checking whether pthreads work with -Kthread... no
       checking whether pthreads work with -kthread... no
       checking for the pthreads library -llthread... no
       checking whether pthreads work with -pthread... yes
       checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
       checking if more special flags are required for pthreads... no
       checking for a BSD-compatible install... /usr/bin/install -c
       checking whether make sets $(MAKE)... (cached) yes
       checking for rst2man... rst2man
       checking for rst2html... rst2html
       checking for dot... no
       configure: WARNING: dot not found - can't generate graphviz output for documentation.
       checking for clock_gettime in -lrt... yes
       checking for dlopen in -ldl... yes
       checking for NcursesW wide-character library... yes
       checking for working ncursesw/curses.h... yes
       checking for working ncursesw.h... no
       checking for working ncurses.h... yes
       checking for library containing pthread_create... none required
       checking for socket in -lsocket... no
       checking for getaddrinfo in -lnsl... yes
       checking for cos in -lm... yes
       checking for pkg-config... /usr/bin/pkg-config
       checking pkg-config is at least version 0.9.0... yes
       checking for PCRE... yes
       checking for PCRE JIT usability... no
       checking edit/readline/readline.h usability... no
       checking edit/readline/readline.h presence... no
       checking for edit/readline/readline.h... no
       checking for LIBEDIT... yes
       checking editline/readline.h usability... yes
       checking editline/readline.h presence... yes
       checking for editline/readline.h... yes
       checking for ANSI C header files... (cached) yes
       checking for sys/wait.h that is POSIX.1 compatible... yes
       checking whether time.h and sys/time.h may both be included... yes
       checking sys/param.h usability... yes
       checking sys/param.h presence... yes
       checking for sys/param.h... yes
       checking for sys/types.h... (cached) yes
       checking sys/endian.h usability... no
       checking sys/endian.h presence... no
       checking for sys/endian.h... no
       checking sys/filio.h usability... no
       checking sys/filio.h presence... no
       checking for sys/filio.h... no
       checking for sys/mount.h... yes
       checking sys/socket.h usability... yes
       checking sys/socket.h presence... yes
       checking for sys/socket.h... yes
       checking sys/statvfs.h usability... yes
       checking sys/statvfs.h presence... yes
       checking for sys/statvfs.h... yes
       checking sys/vfs.h usability... yes
       checking sys/vfs.h presence... yes
       checking for sys/vfs.h... yes
       checking endian.h usability... yes
       checking endian.h presence... yes
       checking for endian.h... yes
       checking execinfo.h usability... yes
       checking execinfo.h presence... yes
       checking for execinfo.h... yes
       checking netinet/in.h usability... yes
       checking netinet/in.h presence... yes
       checking for netinet/in.h... yes
       checking for pthread_np.h... no
       checking stddef.h usability... yes
       checking stddef.h presence... yes
       checking for stddef.h... yes
       checking for stdlib.h... (cached) yes
       checking for unistd.h... (cached) yes
       checking priv.h usability... no
       checking priv.h presence... no
       checking for priv.h... no
       checking for an ANSI C-conforming const... yes
       checking for struct sockaddr.sa_len... no
       ./configure: line 20248: _VARNISH_CHECK_EXPLICIT_BZERO: command not found
       checking return type of signal handlers... void
       checking for size_t... yes
       checking for vprintf... yes
       checking for _doprnt... no
       checking for strerror... yes
       checking whether strerror_r is declared... yes
       checking for strerror_r... yes
       checking whether strerror_r returns char *... yes
       checking for dladdr... no
       checking for socket... yes
       checking for explicit_bzero... no
       checking for nanosleep... yes
       checking for setppriv... no
       checking for fallocate... yes
       checking for closefrom... no
       checking for vsyslog... yes
       checking for sigaltstack... yes
       checking for pthread_set_name_np... no
       checking for pthread_mutex_isowned_np... no
       checking for pthread_timedjoin_np... yes
       checking whether we have support for visibility attributes... yes
       checking for malloc_conf in -ljemalloc... no
       configure: WARNING: No system jemalloc found, using system malloc
       checking for setproctitle... no
       checking for library containing backtrace... none required
       checking whether daemon() works... checking for daemon... yes
       checking for special C compiler options needed for large files... no
       checking for _FILE_OFFSET_BITS value needed for large files... no
       checking for clock_gettime... yes
       checking for gethrtime... no
       checking for kqueue... no
       checking for epoll_ctl... yes
       checking for port_create... no
       checking for python3... no
       checking for python3.1... no
       checking for python3.2... no
       checking for python2.7... no
       checking for python2.6... python2.6
       checking whether SO_ACCEPTFILTER is declared... no
       checking whether SO_RCVTIMEO works... yes
       checking whether SO_SNDTIMEO works... yes
       checking for TCP_KEEP(CNT|IDLE|INTVL) socket options... yes
       checking for TCP_FASTOPEN socket option... no
       checking if LD -Wl,--version-script works... yes
       checking whether C compiler accepts -Werror=unused-result... no
       checking whether C compiler accepts -Wunused-result... no
       checking whether C compiler accepts -fstack-protector... yes
       checking whether the linker accepts -fstack-protector... yes
       configure: creating ./config.status
       config.status: creating Makefile
       config.status: creating bin/Makefile
       config.status: creating bin/varnishadm/Makefile
       config.status: creating bin/varnishd/Makefile
       config.status: creating bin/varnishlog/Makefile
       config.status: creating bin/varnishstat/Makefile
       config.status: creating bin/varnishtop/Makefile
       config.status: creating bin/varnishhist/Makefile
       config.status: creating bin/varnishtest/Makefile
       config.status: creating bin/varnishncsa/Makefile
       config.status: creating doc/Makefile
       config.status: creating doc/graphviz/Makefile
       config.status: creating doc/sphinx/Makefile
       config.status: creating doc/sphinx/conf.py
       config.status: creating etc/Makefile
       config.status: creating include/Makefile
       config.status: creating lib/Makefile
       config.status: creating lib/libvarnish/Makefile
       config.status: creating lib/libvarnishapi/Makefile
       config.status: creating lib/libvarnishtools/Makefile
       config.status: creating lib/libvarnishcompat/Makefile
       config.status: creating lib/libvcc/Makefile
       config.status: creating lib/libvgz/Makefile
       config.status: creating lib/libvmod_debug/Makefile
       config.status: creating lib/libvmod_std/Makefile
       config.status: creating lib/libvmod_directors/Makefile
       config.status: creating man/Makefile
       config.status: creating varnishapi.pc
       config.status: creating varnishapi-uninstalled.pc
       config.status: creating config.h
       config.status: config.h is unchanged
       config.status: executing depfiles commands
       config.status: executing libtool commands
       config.status: executing mkdir commands
       make  all-recursive
       make[1]: Entering directory `/build/varnish-cache-varnish-4.1.9'
       Making all in include
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9/include'
       make  all-am
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/include'
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/include'
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9/include'
       Making all in lib
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib'
       Making all in libvarnishcompat
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishcompat'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishcompat'
       Making all in libvarnish
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnish'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnish'
       Making all in libvarnishapi
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishapi'
       make  all-am
       make[4]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishapi'
       make[4]: Nothing to be done for `all-am'.
       make[4]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishapi'
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishapi'
       Making all in libvarnishtools
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishtools'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvarnishtools'
       Making all in libvcc
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvcc'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvcc'
       Making all in libvgz
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvgz'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvgz'
       Making all in libvmod_debug
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvmod_debug'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvmod_debug'
       Making all in libvmod_std
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvmod_std'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvmod_std'
       Making all in libvmod_directors
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib/libvmod_directors'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib/libvmod_directors'
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/lib'
       make[3]: Nothing to be done for `all-am'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib'
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9/lib'
       Making all in bin
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin'
       Making all in varnishadm
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishadm'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishadm'
       Making all in varnishd
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishd'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishd'
       Making all in varnishhist
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishhist'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishhist'
       Making all in varnishlog
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishlog'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishlog'
       Making all in varnishncsa
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishncsa'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishncsa'
       Making all in varnishstat
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishstat'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishstat'
       Making all in varnishtest
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishtest'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishtest'
       Making all in varnishtop
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin/varnishtop'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin/varnishtop'
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/bin'
       make[3]: Nothing to be done for `all-am'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin'
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9/bin'
       Making all in etc
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9/etc'
       make[2]: Nothing to be done for `all'.
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9/etc'
       Making all in doc
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9/doc'
       Making all in graphviz
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/doc/graphviz'
       make[3]: Nothing to be done for `all'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/doc/graphviz'
       Making all in sphinx
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/doc/sphinx'
       test -d reference || mkdir reference
       cp ../../lib/libvmod_std/vmod_std.rst reference/vmod_std.generated.rst
       cp ../../lib/libvmod_directors/vmod_directors.rst reference/vmod_directors.generated.rst
       make  all-am
       make[4]: Entering directory `/build/varnish-cache-varnish-4.1.9/doc/sphinx'
       make[4]: Nothing to be done for `all-am'.
       make[4]: Leaving directory `/build/varnish-cache-varnish-4.1.9/doc/sphinx'
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/doc/sphinx'
       make[3]: Entering directory `/build/varnish-cache-varnish-4.1.9/doc'
       make[3]: Nothing to be done for `all-am'.
       make[3]: Leaving directory `/build/varnish-cache-varnish-4.1.9/doc'
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9/doc'
       Making all in man
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9/man'
       make[2]: Nothing to be done for `all'.
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9/man'
       make[2]: Entering directory `/build/varnish-cache-varnish-4.1.9'
       make[2]: Leaving directory `/build/varnish-cache-varnish-4.1.9'
       make[1]: Leaving directory `/build/varnish-cache-varnish-4.1.9'
       + mkdir -p m4
       + aclocal -I m4
       + libtoolize --copy --force
       libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `.'.
       libtoolize: copying file `./ltmain.sh'
       libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
       libtoolize: copying file `m4/libtool.m4'
       libtoolize: copying file `m4/ltoptions.m4'
       libtoolize: copying file `m4/ltsugar.m4'
       libtoolize: copying file `m4/ltversion.m4'
       libtoolize: copying file `m4/lt~obsolete.m4'
       libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'
       + autoheader
       + automake --add-missing --copy --foreign
       + autoconf
       checking build system type... x86_64-unknown-linux-gnu
       checking host system type... x86_64-unknown-linux-gnu
       checking target system type... x86_64-unknown-linux-gnu
       checking for gcc... gcc
       checking for C compiler default output file name... a.out
       checking whether the C compiler works... yes
       checking whether we are cross compiling... no
       checking for suffix of executables...
       checking for suffix of object files... o
       checking whether we are using the GNU C compiler... yes
       checking whether gcc accepts -g... yes
       checking for gcc option to accept ISO C89... none needed
       checking how to run the C preprocessor... gcc -E
       checking for grep that handles long lines and -e... /bin/grep
       checking for egrep... /bin/grep -E
       checking for ANSI C header files... yes
       checking for sys/types.h... yes
       checking for sys/stat.h... yes
       checking for stdlib.h... yes
       checking for string.h... yes
       checking for memory.h... yes
       checking for strings.h... yes
       checking for inttypes.h... yes
       checking for stdint.h... yes
       checking for unistd.h... yes
       checking minix/config.h usability... no
       checking minix/config.h presence... no
       checking for minix/config.h... no
       checking whether it is safe to define __EXTENSIONS__... yes
       checking for a BSD-compatible install... /usr/bin/install -c
       checking whether build environment is sane... yes
       checking for a thread-safe mkdir -p... /bin/mkdir -p
       checking for gawk... gawk
       checking whether make sets $(MAKE)... yes
       checking for style of include used by make... GNU
       checking dependency style of gcc... gcc3
       checking for gcc... (cached) gcc
       checking whether we are using the GNU C compiler... (cached) yes
       checking whether gcc accepts -g... (cached) yes
       checking for gcc option to accept ISO C89... (cached) none needed
       checking for gcc option to accept ISO C99... -std=gnu99
       checking how to run the C preprocessor... gcc -E
       checking for a BSD-compatible install... /usr/bin/install -c
       checking for a sed that does not truncate output... /bin/sed
       checking for fgrep... /bin/grep -F
       checking for ld used by gcc -std=gnu99... /usr/bin/ld
       checking if the linker (/usr/bin/ld) is GNU ld... yes
       checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
       checking the name lister (/usr/bin/nm -B) interface... BSD nm
       checking whether ln -s works... yes
       checking the maximum length of command line arguments... 1572864
       checking whether the shell understands some XSI constructs... yes
       checking whether the shell understands "+="... yes
       checking for /usr/bin/ld option to reload object files... -r
       checking for objdump... objdump
       checking how to recognize dependent libraries... pass_all
       checking for ar... ar
       checking for strip... strip
       checking for ranlib... ranlib
       checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
       checking for dlfcn.h... yes
       checking for objdir... .libs
       checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
       checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
       checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
       checking if gcc -std=gnu99 static flag -static works... no
       checking if gcc -std=gnu99 supports -c -o file.o... yes
       checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
       checking whether the gcc -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
       checking whether -lc should be explicitly linked in... no
       checking dynamic linker characteristics... GNU/Linux ld.so
       checking how to hardcode library paths into programs... immediate
       checking whether stripping libraries is possible... yes
       checking if libtool supports shared libraries... yes
       checking whether to build shared libraries... yes
       checking whether to build static libraries... yes
       checking whether make sets $(MAKE)... (cached) yes
       checking for gawk... (cached) gawk
       checking for gcc... (cached) gcc
       checking whether we are using the GNU C compiler... (cached) yes
       checking whether gcc accepts -g... (cached) yes
       checking for gcc option to accept ISO C89... (cached) none needed
       checking how to run the C preprocessor... gcc -E
       checking for a BSD-compatible install... /usr/bin/install -c
       checking whether ln -s works... yes
       checking whether make sets $(MAKE)... (cached) yes
       checking for ranlib... (cached) ranlib
       checking for md2man-roff... no
       configure: WARNING: md2man not found - not building man pages
       checking for pkg-config... /usr/bin/pkg-config
       checking pkg-config is at least version 0.9.0... yes
       checking for python3... no
       checking for python3.1... no
       checking for python3.2... no
       checking for python2.7... no
       checking for python2.6... python2.6
       checking for stdlib.h... (cached) yes
       checking for string.h... (cached) yes
       checking for ANSI C header files... (cached) yes
       checking sys/stdlib.h usability... no
       checking sys/stdlib.h presence... no
       checking for sys/stdlib.h... no
       checking for inline... inline
       checking for size_t... yes
       checking for strchr... yes
       ./configure: line 15018: syntax error near unexpected token `fi'
       ./configure: line 15018: `fi'
       make: *** No targets specified and no makefile found.  Stop.
```

**Comment by andrew-canaday** [comment]
@gsdevme could you do me a favor and paste the output of `sed -n 14900,15100p ./configure` into [Issue #2](https://github.com/NYTimes/libvmod-queryfilter/issues/2)?

**Comment by gsdevme** [comment]
screen shot 2018-04-03 at 17 20 08

@andrew-canaday I've just rebased this and enabled Travis on my fork and its working now, so perhaps can add some tests to run after its compiled but the automation would at least check it can be compiled on each platform

**Comment by gsdevme** [comment]
One thing I did notice is the `make` builds into `/usr/local/lib/varnish/vmods/` whereas CentOS 6.x actually wants `/usr/lib64/varnish/vmods/` 

After copying the files across I could boot Varnish with the plugin installed 🎉

**Comment by gsdevme** [comment]
https://travis-ci.org/gsdevme/libvmod-queryfilter/builds/361739225

**Comment by andrew-canaday** [comment]
_Thank you for this!_ Will look be looking at this early next week while setting up CI for the 1.0 release.

**Comment by gsdevme** [comment]
Awesome, let me know if there is anything I can do to help. This is really just one way to do Im sure there might be a better way that using kitchen-ci @andrew-canaday

**Comment by andrew-canaday** [comment]
Hey, @gsdevme I'm going to close this out _for now_, but will add you as a contributor when we push the upcoming CI changes / will re-open, if necessary. (Please feel free to re-open if you find this to be problematic or want to continue discussing this thread, in particular).

**Pull request closed without merging**
